# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e590d7c96b480dc20aac5b72fb22b4cc49edf6a9b247e5d68d5af9ff56499939b9316ddf90ab0e44d5fc974010081d0ecd56ea05910fe757af9dede23c55ed4e

test:
  secret_key_base: f46bf0b19910a5884b503809ce1c4d2bc09eb73307fa760843fda4a2624b17f961d08be90b592eacf0af27cc83706863422e3dee76ea9e5133847065225acdcc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
